s = "GCTTGTCCGTTCCATTACTGCCGGGCAACGACAATTCCTTAGCCGTGGTGTTATGGCGTACCAGGCTAACGGGTTGTAGCCATACCTGTTTGCGGCTTCTCGTGGACGGCAGCCGTTAGGTAGTTTGATAAGCTTCGTCCGTCTATTCAGATAGGTCACTAGGAACCCATTGATGTGTAATTGTCTACCGACAGCTTGATAAACGTCGCCTGCTTCGGGAGGCTCCATTCGTGGCCTCCCCGAAATCCGTCACGCCCATGCATGTGTTTGAACGTCCCCAGATAGCATCCGCTTCTCGACACCAGTAAAAATAACTTACTTCATTATCAAAGTCTCACACTTCCCGATGTCAGATGTATCTCGGGCGGTTTTAATGAAATCACACGAGCTAATACTAGTGAGCTCTAATTAAAGCATGCCCGAAAAAGGTCTGAAGAGCTCCTGAACAATCGAGATGAGGATGATCTGTTGGAATCGATTCGGGACACCCAGAGTCTCTCGGCAGCAAATCTGGCTCGAATAGCGGTCGCACTGCCGACTTCTGTTTAAAAACGCTACATCCACCGGCCTAACTGGCGAGGGACGACGACTCCCCCGCCTGAGCTTGTCCAGGTTGCTCATGTAATCAACAACGCTGCAGCGTCGGGACACTGCTGCGTTTGCTGTGCGAGTGGAAGGTGTTTTCGGAAGAAGTATTGCGGATCTTGGAACTAAGCGTTGTAATCCTCGAAAGCGAACATCACGAAATTACATTCCCAAGACGGTCGGCAGTGTCTTGGGCATTGGAACGGGAGACGTTGTCGACCTCCGATGAAGGAATCAAGCCAATGGATGTCGCACGGAAGGAACGACACAGGTCCCGGTTCTACAT"
a_counter = 0
c_counter = 0
g_counter = 0
t_counter = 0

for c in s:
    if c == 'A':
        a_counter += 1
    elif c == 'C':
        c_counter += 1
    elif c == 'G':
        g_counter += 1
    elif c == 'T':
        t_counter += 1
print(a_counter, c_counter, g_counter, t_counter)