# Reverse complement of a DNA sequence

s = "CCAGACGATACCACGCTCAGCTTCCAAAGTAGATGTTCGGTCGAATGCATGGGCCAGGGTCTATCTGATACCGTGCCAGCAGCGAAGACAACGAGTTAGTTATGGCGTGTGCCGTAGGTCGAGAATTGGACAAAAGAGCATCTTAACACATACCCTCGAGAGAGTCTTCTGAGTGGGTTCGCTATTTTGTTTCCGAGATACATACCGTGGTAGAATGAAACCTCCACGACGCTTGCGTTGTATTATGGAGAAGCTAGATCGTGCCCTTTGGTCCCTCCCACTAATCTGCTAACACATTTAATGGTGAGAAAATGTACAAAATGTATAGGACGTCGCTAGTCCTCGTCTGAACAGTTTCGTTACTACTGACGAACTTATTAACCTTCAGTCACACCTAATGTTAGGGAACGGATCCTAAACTGGCCTGGTATTCGTGGTTAATAAACCATTTGTTGACTATAAATGTGCCAGGATAGGTCTGAGGCCCATGGTACGAGTGCCGGTCGGTCATGGGAAGGGGGAGAAGACAATGCTAGGGGTGAGAAAAGTAGAAAAGACGCACTCGCAAATTCCCTGAGACGTCCGAAGTTGGCAGTACCCCTTTGATAGAGCTCGTCTAGTTGCAGGAGCCATCTAGACGCACGAATGTGATAAGTGGATCCTTACTGTAACTTAGTGTACCGAGTTTAAGGACTAGATCAAATTCCACTGTGGAAGATGGTCGTGCGCATCGATAACGCAGCCCCGCATGTTGAAACTCGGGCATCAGAGTTGCAAAGCATGATACCCCATTAAGGCCAAGGACCGATTATCCCATACCAGGCAACAGAGTCTCGACGTGCACGTTTCTATTGCAGCCTATGAATGAGGAATAAT"

reverse_sequence = ""
reverse_complement = ""

# Reverse the DNA sequence
for base in s:
    reverse_sequence = base + reverse_sequence

# Build complementary sequence
for base in reverse_sequence:
    if base == 'A':
        reverse_complement += 'T'
    elif base == 'C':
        reverse_complement += 'G'
    elif base == 'G':
        reverse_complement += 'C'
    elif base == 'T':
        reverse_complement += 'A'

print(reverse_complement)
